services:
    core:
        build:
            context: ./trillian/
            dockerfile: ./config/core/Dockerfile
            args:
            - GOFLAGS
        environment:
        - MYSQL_HOST=mysql
        - MYSQL_ROOT_PASSWORD=beeblebrox
        - MYSQL_USER=test
        - MYSQL_DATABASE=cttest
        - MYSQL_PASSWORD=zaphod
        restart: always
        depends_on:
        - mysql

    tlserver:
        build:
            context: ./trillian/
            dockerfile: ./config/tlserver/Dockerfile
            args:
            - GOFLAGS
        environment:
        - MYSQL_HOST=mysql
        - MYSQL_ROOT_PASSWORD=beeblebrox
        - MYSQL_USER=test
        - MYSQL_DATABASE=cttest
        - MYSQL_PASSWORD=zaphod
        restart: always
        ports:
        - '8090:8090'
        - '8091:8091'
        expose:
        - '8090'
        - '8091'
        depends_on:
        - mysql

    tlsigner:
        build:
            context: ./trillian
            dockerfile: ./config/tlsigner/Dockerfile
            args:
            - GOFLAGS
        restart: always
        environment:
        - MYSQL_HOST=mysql
        - MYSQL_ROOT_PASSWORD=beeblebrox
        - MYSQL_USER=test
        - MYSQL_DATABASE=cttest
        - MYSQL_PASSWORD=zaphod
        ports:
        - '8092:8091'
        depends_on:
        - mysql

    ct:
        build: ./certificate-transparency-go/
        restart: always
        environment:
        - MYSQL_HOST=mysql
        - MYSQL_ROOT_PASSWORD=beeblebrox
        - MYSQL_USER=test
        - MYSQL_DATABASE=cttest
        - MYSQL_PASSWORD=zaphod
        ports:
        - '8090:6962'
        - '8091:6965'
        expose:
        - '6962'
        - '6965'
        depends_on:
        - mysql

    mysql:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
        - MYSQL_ROOT_PASSWORD=beeblebrox
        - MYSQL_DATABASE=cttest
        - MYSQL_USER=test
        - MYSQL_PASSWORD=zaphod
        ports:
        # <Port exposed> : < MySQL Port running inside container>
        - '3306:3306'
        expose:
        - '3306'
        volumes:
        - data_volume:/data/db


volumes:
    data_volume:
    source_code:

version: '3'

